<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.77.0" />
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bikontrol.Application\Bikontrol.Application.csproj" />
    <ProjectReference Include="..\Bikontrol.Domain\Bikontrol.Domain.csproj" />
    <ProjectReference Include="..\Bikontrol.Persistence\Bikontrol.Persistence.csproj" />
    <ProjectReference Include="..\Bikontrol.Shared\Bikontrol.Shared.csproj" />
  </ItemGroup>

</Project>
