// <auto-generated />
using System;
using Bikontrol.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bikontrol.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115125230_AddMaintenanceTables")]
    partial class AddMaintenanceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bikontrol.Domain.Entities.Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultKmInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultTimeIntervalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Km");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DefaultKmInterval = 1500,
                            Description = "Reemplazo del aceite del motor.",
                            IsEnabled = true,
                            Name = "Cambio de Aceite",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DefaultKmInterval = 1500,
                            Description = "Sustitución del filtro de aceite del motor.",
                            IsEnabled = true,
                            Name = "Cambio de Filtro de Aceite",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DefaultTimeIntervalWeeks = 2,
                            Description = "Limpieza y lubricación de la cadena de transmisión.",
                            IsEnabled = true,
                            Name = "Lubricación y Limpieza de Cadena",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DefaultKmInterval = 20000,
                            Description = "Chequeo completo del estado general de la motocicleta.",
                            IsEnabled = true,
                            Name = "Revisión General",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DefaultKmInterval = 5000,
                            Description = "Revisión preventiva del estado general de la motocicleta.",
                            IsEnabled = true,
                            Name = "Mantenimiento Preventivo",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            DefaultKmInterval = 6000,
                            Description = "Limpieza o reemplazo del filtro de aire.",
                            IsEnabled = true,
                            Name = "Filtro de Aire",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            DefaultKmInterval = 8000,
                            Description = "Reemplazo o limpieza del filtro de gasolina.",
                            IsEnabled = true,
                            Name = "Filtro de Gasolina",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            DefaultTimeIntervalWeeks = 1,
                            Description = "Verificación y ajuste de la presión de las llantas.",
                            IsEnabled = true,
                            Name = "Presión de Llantas",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            DefaultKmInterval = 8000,
                            Description = "Revisión y reemplazo de las pastillas de freno delanteras.",
                            IsEnabled = true,
                            Name = "Pastillas de Freno Delanteras",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            DefaultKmInterval = 8000,
                            Description = "Revisión y reemplazo de las pastillas de freno traseras.",
                            IsEnabled = true,
                            Name = "Pastillas de Freno Traseras",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            DefaultKmInterval = 25000,
                            Description = "Revisión del disco de freno delantero.",
                            IsEnabled = true,
                            Name = "Disco de Freno Delantero",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            DefaultKmInterval = 25000,
                            Description = "Revisión del disco de freno trasero.",
                            IsEnabled = true,
                            Name = "Disco de Freno Trasero",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            DefaultTimeIntervalWeeks = 52,
                            Description = "Reemplazo del líquido de frenos delantero.",
                            IsEnabled = true,
                            Name = "Líquido de Frenos Delantero",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            DefaultTimeIntervalWeeks = 52,
                            Description = "Reemplazo del líquido de frenos trasero.",
                            IsEnabled = true,
                            Name = "Líquido de Frenos Trasero",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            DefaultTimeIntervalWeeks = 52,
                            Description = "Revisión del estado y carga de la batería.",
                            IsEnabled = true,
                            Name = "Batería",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            DefaultKmInterval = 10000,
                            Description = "Revisión de suspensión delantera y trasera.",
                            IsEnabled = true,
                            Name = "Suspensión",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            DefaultTimeIntervalWeeks = 8,
                            Description = "Ajuste general de tornillería.",
                            IsEnabled = true,
                            Name = "Tornillería",
                            TrackingType = "Time"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            DefaultKmInterval = 8000,
                            Description = "Ajuste de holguras de válvulas.",
                            IsEnabled = true,
                            Name = "Calibración de Válvulas",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            DefaultKmInterval = 12000,
                            Description = "Revisión o reemplazo del piñón.",
                            IsEnabled = true,
                            Name = "Kit de Arrastre - Piñón",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            DefaultKmInterval = 12000,
                            Description = "Revisión o reemplazo de la corona.",
                            IsEnabled = true,
                            Name = "Kit de Arrastre - Corona",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            DefaultKmInterval = 12000,
                            Description = "Revisión o reemplazo de la cadena.",
                            IsEnabled = true,
                            Name = "Kit de Arrastre - Cadena",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            DefaultKmInterval = 500,
                            Description = "Ajuste de la tensión de la cadena.",
                            IsEnabled = true,
                            Name = "Tensión de Cadena",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            DefaultKmInterval = 8000,
                            Description = "Ajuste de mezcla/ralentí o sistema de inyección.",
                            IsEnabled = true,
                            Name = "Sincronización",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            DefaultKmInterval = 8000,
                            Description = "Reemplazo de bandas de freno (frenos de tambor).",
                            IsEnabled = true,
                            Name = "Bandas de Freno",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            DefaultKmInterval = 4000,
                            Description = "Revisión o reemplazo de bujía.",
                            IsEnabled = true,
                            Name = "Bujía",
                            TrackingType = "Km"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            DefaultKmInterval = 15000,
                            Description = "Revisión del desgaste de los neumáticos.",
                            IsEnabled = true,
                            Name = "Neumáticos",
                            TrackingType = "Km"
                        });
                });

            modelBuilder.Entity("Bikontrol.Domain.Entities.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Displacement")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default.png");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Km")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("Bikontrol.Domain.Entities.UserMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("KmInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("TimeIntervalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Km");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMaintenanceTypes", (string)null);
                });

            modelBuilder.Entity("Bikontrol.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bikontrol.Domain.Entities.Motorcycle", b =>
                {
                    b.HasOne("Bikontrol.Persistence.Entities.User", "User")
                        .WithMany("Motorcycles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bikontrol.Domain.Entities.UserMaintenance", b =>
                {
                    b.HasOne("Bikontrol.Domain.Entities.Maintenance", "BaseType")
                        .WithMany("UserMaintenanceTypes")
                        .HasForeignKey("BaseTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bikontrol.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bikontrol.Domain.Entities.Maintenance", b =>
                {
                    b.Navigation("UserMaintenanceTypes");
                });

            modelBuilder.Entity("Bikontrol.Persistence.Entities.User", b =>
                {
                    b.Navigation("Motorcycles");
                });
#pragma warning restore 612, 618
        }
    }
}
